[package]
name = "tree-sitter-elsa"
description = "Elsa grammar for the tree-sitter parsing library"
version = "1.0.0"
author = [
	"Miles Glapa-Grossklag <miles@glapa-grossklag.com>",
	"Amaan Qureshi <amaanq12@gmail.com>",
]
keywords = ["incremental", "parsing", "elsa"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/tree-sitter/tree-sitter-elsa"
edition = "2018"
license = "MIT"

build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~0.20"

[build-dependencies]
cc = "1.0"
