#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

function checkout() {
  repo=$1; url=$2; sha=$3

  if [ ! -d "$repo" ]; then
    git clone "https://github.com/$url" "$repo"
  fi

  pushd "$repo"
  git fetch && git reset --hard "$sha"
  popd
}

checkout examples/elsa ucsd-progsys/elsa 00e0bb97326cce5329dee8652f1531a4ed111d19

known_failures="$(cat script/known_failures.txt)"

# Remove input directories
find examples -type d -name input -exec rm -rf {} +

tree-sitter parse -q \
  'examples/**/*.lc' \
  "$(for file in $known_failures; do echo "!${file}"; done)"

example_count=$(find examples -name '*.lc' | wc -l)
failure_count=$(wc -w <<< "$known_failures")
success_count=$(( example_count - failure_count ))
success_percent=$(bc -l <<< "100*${success_count}/${example_count}")

printf \
  "Successfully parsed %d of %d example files (%.1f%%)\n" \
  $success_count "$example_count" "$success_percent"
